### ISSUE TITLE
Site Map Feature Request

### ISSUE THREAD

**Issue by esherwoo77** [tbep-tech/tbeptools#34]
@fawda123 : It would be nice to be able to export a site map of the EPC chl-a or la data for a particular period of time other than the annual timestep. For instance export a map image of chl-a data for Nov. 2020 or export a map image for averages over the May - Oct. 2020 period.

**Comment by fawda123** [comment]
@esherwoo77 does this work?  I decided to show the results as continuous values since the thresholds/targets don't make sense at a monthly level.  You can change the parameters as chlorophyll or light attenuation with `param = "chla"` or `param = "la"`.  An individual month can also be shown, e.g., for September only, `mosel = 9`.
```
show_sitemap(epcdata, yrsel = 2018, mosel = c(7, 9))
```
![image](https://user-images.githubusercontent.com/3086881/101522546-6554ed00-3955-11eb-9934-79a93358197d.png)

**Comment by esherwoo77** [comment]
@fawda123 Yes, I think this is perfect. Thanks for the quick turn-around.
