### ISSUE TITLE
add tests and vignettes for show_tldcrkradar

### ISSUE THREAD

**Issue by fawda123** [tbep-tech/tbeptools#41]
Need to add tests, include vignette entry.  Also clean up code, there's a lot of fluff.

**Comment by fawda123** [comment]
done here 188a4320ab8b12002ee2aea1dd1949a49d740c51

**Comment by mikewessel** [comment]
Thanks Marcus! – I will work to add/update vignettes etc to jive with manuscript and submit pull request.  Sent from Mail for Windows 10 From: Marcus W BeckSent: Sunday, June 20, 2021 12:10 PMTo: tbep-tech/tbeptoolsCc: SubscribedSubject: Re: [tbep-tech/tbeptools] add tests and vignettes for show_tldcrkradar (#41) Closed #41.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avast.com
